### PR TITLE
Development rishabh

### PR DESCRIPTION
**Pull request by rishi1596**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | yes
| Fixed issues  | #1 #4 and partial #5 

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by tanmaysawaji** [comment]
I will review this request as soon as I can

**Comment by pranavacharya** [comment]
Should we merge this after completing #5 ?

**Comment by pranavacharya** [comment]
> Should we merge this after completing #5 ?

Or should we move #5 to another PR ?

**Comment by pranavacharya** [comment]
Login page with google Auth looks good to me.

Although on directly following commands from README didn't work for me. I'll update the readme and create a PR.

**Comment by pranavacharya** [comment]
We need to work on dashboard, I am done with lat lng conversion task, should I pick this up ?

**Comment by pranavacharya** [comment]
TODO: change mock API to actual API enpoints

**Comment by pranavacharya** [comment]
added #17 for updating readme for steps for running react project

**Comment by rishi1596** [comment]
> TODO: change mock API to actual API enpoints

Yes, once the module is ready #12

**Comment by rishi1596** [comment]
> > Should we merge this after completing #5 ?
> 
> Or should we move #5 to another PR ?

We can continue that after merge because its an independent feature

**Review by pranavacharya — APPROVED** [review]
lgtm

**Pull request merged**
