### PR TITLE
Db middleware integration

### PR DESCRIPTION
**Pull request by pranavacharya**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | not present
| Fixed issues  | #32 

Integration of db_middleware service and queue_worker

### CODE REVIEW

**Comment by pranavacharya** [comment]
Need to add few more parameter from queue_worker (start_time, end_time, requestID) 
Tested rest of the  parameters

**Comment by pranavacharya** [comment]
#34  pending

**Comment by pranavacharya** [comment]
This branch is ready for merge.

TODO: complete updateStatusOfRequestInDB function

**Review by rishi1596 — APPROVED** [review]
great. Will have to look closely at all the changes made on db_middleware for further development.

**Pull request merged**
