### PR TITLE
Queue worker - rabbitmq consumer and publish data to API endpoint

### PR DESCRIPTION
**Pull request by pranavacharya**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | not present
| Fixed issues  | #7 

Added rabbitmq consumer code, 
pushesh request data to API endpoint

TODO: need to modify API endpoint

### CODE REVIEW

**Review by rishi1596 — APPROVED** [review]

**Comment by rishi1596** [comment]
Todo:1. confirm API endpoint to call to nodejs server (To be decided IP and port)
2. We will be using the following date format throughout the system DD-MM-YYYY format.

**Comment by pranavacharya** [comment]
I'll update the readme with the message format the consumer is expecting from rabbitmq queue

TODO: update readme

**Comment by pranavacharya** [comment]
TODO: document queue name in rabbitmq, connection config

**Review by tanmaysawaji — APPROVED** [review]
Works fine!

**Pull request merged**
